### ISSUE TITLE
New Atomic updates fail to trigger parsing in Matrix Blocks

### ISSUE THREAD

**Issue by AugustMiller** [besteadfast/craft-preparse-field#62]
From Adrienne, in Craft Discord:
https://discordapp.com/channels/456442477667418113/575387375610626063/734856474735542433

I think we identified that because Matrix Block data isn't sent back to the server (when no changes are detected in the browser) as of 3.4's "delta" updates, values that *ought* to change based on the parent Entry aren't actually updated.

**Comment by adrienne** [comment]
@AugustMiller @jalendport - Yup, that's me, and what seems to happen is that if nothing *else* (besides the preparse) has changed in a Matrix field, it doesn't get resaved when the entry itself is saved.

**Comment by monachilada** [comment]
@jalendport I think #66 should also solve this issue, but some additional testing would be appreciated. I have a nagging feeling I'm missing something since I'm not so familiar with the codebase as others might be.

**Comment by adrienne** [comment]
@jalendport any more info here?

**Comment by jalendport** [comment]
Hey @adrienne, so very sorry for the delay. I just released 1.2.3 with Mike's PR; haven't had a chance to test against your exact issue here but if you'd like to update and see if it solves your problem that would be awesome. Otherwise, I'll try to test this for you some point in the next week...

**Comment by jalendport** [comment]
Tested this with Preparse 1.2.3 on the latest version of Craft and everything seems to function normally now. (Namely, a preparse field with `{{ random(50, 100) }}` will now generate a new random number on every save.)
