### ISSUE TITLE
Matrix blocks removed from revisions

### ISSUE THREAD

**Issue by brandonkelly** [besteadfast/craft-preparse-field#64]
When an entry with both Matrix and Preparse fields is saved, and one of the Matrix blocks are edited, then all of the Matrix blocks will be missing from the new revision that is created for the entry save.

Steps to reproduce:

1. Install Craft 3.5.15.1 (to avoid https://github.com/craftcms/cms/issues/7199) and Preparse
2. Create a Matrix field
3. Create a Preparse field (leave “Parse before save” set to “no”)
4. Create a section and entry type with both fields assigned to it
5. Create a new entry with that entry type, with at least one Matrix block; save it via “Save and continue editing”
6. Change the entry’s title, but not its Matrix field; save it via “Save and continue editing”
7. Change the entry’s title again, save again via “Save and continue editing”

You should now have two revisions listed for the entry. Go to the first revision and notice that there are no Matrix blocks, even though it should. Then go to the second revision and notice that it has the Matrix blocks you’d expect to be there (because the Matrix field hadn’t been edited on that second save).

**Comment by monachilada** [comment]
@jalendport Genuine question, from a logical point of view, would it make sense for this change to find its way into the EVENT_BEFORE_SAVE section of the plugin too? I can't think of a reason preparse should run before saving a revision, but maybe I'm missing something?

**Comment by brandonkelly** [comment]
(Probably a good idea.)

**Comment by Mosnar** [comment]
This seems like it's still an issue (or perhaps it manifested a new way) - I just tested on two separate installations, both on Preparse 1.2.2 and Craft CMS 3.5.16 and both installations lost all of their Matrix content in the revision.

**Comment by monachilada** [comment]
@Mosnar Yes, I've submitted #66 in the hopes of fixing precisely that. Maybe you could try my branch out locally to test if that fixes things? I'd appreciate another set of eyes on the changes in my PR to make sure I'm not missing something.

@jalendport Do you think you might have a chance to review that PR in the near future to see if it fixes the latent issues?

**Comment by Mosnar** [comment]
@monachilada I just tested your fork and it does indeed appear to work on newly created entries and entries that start with no blocks; however, it seems like pre-existing entries with blocks are still losing their content for some reason. Are you able to reproduce that behavior?

**Comment by jalendport** [comment]
@Mosnar going to check into this here soon for you...
