### ISSUE TITLE
When Using Preparse field in an entry with a matrix field and "Saving as new entry", the matrix field is emptied in the original entry and the newly created copy

### ISSUE THREAD

**Issue by Chris7Ford** [besteadfast/craft-preparse-field#69]
Craft version: 3.5.17.1
Preparse Field version: 1.2.2

I have an entry with a preparse field and a matrix block field that consists of an entry relationship and a number:

![Screen Shot 2021-02-22 at 1 24 09 PM](https://user-images.githubusercontent.com/29003743/108753526-dcd8f800-7512-11eb-8809-d072ef0c8ef0.png)

When I click "Save as a new entry" with intentions of saving a copy, a copy is created, but the matrix block is emptied in the copy AND in the original entry.

![Screen Shot 2021-02-22 at 1 26 01 PM](https://user-images.githubusercontent.com/29003743/108753585-eeba9b00-7512-11eb-8320-86b7ebc63606.png)

![Screen Shot 2021-02-22 at 1 28 14 PM](https://user-images.githubusercontent.com/29003743/108753613-f7ab6c80-7512-11eb-906d-a524fde896c3.png)

The weird thing is, when the preparse field is removed from the entry type and I do this same thing, the matrix is left intact as expected, and the data is present in the original entry and the copy. Has anyone reported anything like this?

Note: This only occurs when "Save as a new entry" is selected, it does not appear to be an issue with a normal save or "Save and continue editing"

**Comment by jalendport** [comment]
Hey @Chris7Ford, I believe this was fixed in version 1.2.3 (just released that today); could you update and let me know if you're still having problems? Thanks...

**Comment by cherrykoda** [comment]
@jalendport I am also running into this issue following the 1.2.3 release. Im also getting an error:

"Trying to get property 'id' of non-object"

![image](https://user-images.githubusercontent.com/3789834/108910042-4e887300-75f3-11eb-9e12-3e55d2182946.png)

**Comment by Chris7Ford** [comment]
@jalendport For us this update resolved the issue, thank you for your help and prompt response. Have a great week! 👍

**Comment by jalendport** [comment]
@cherrykoda tracking that issue in #70; going to close this issue since 1.2.3 resolved the original problem.

**Comment by jalendport** [comment]
@cherrykoda @Chris7Ford are either of you running multisite?

**Comment by cherrykoda** [comment]
@jalendport jalendport - yes I am using multisite.
