### ISSUE TITLE
Error when trying to save a new global set

### ISSUE THREAD

**Issue by bellamystudio** [besteadfast/craft-preparse-field#71]
I'm trying to create a new global set with one (plain text) field in it but whenever I save I get the following Yii error; I'm using version 1.2.4 of the plugin on Craft 3.6.7 on PHP 7.3.24

yii\base\ErrorException: Trying to get property 'id' of non-object in /vendor/besteadfast/craft-preparse-field/src/PreparseField.php:118
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(76): craft\web\ErrorHandler->handleError()
#1 /vendor/besteadfast/craft-preparse-field/src/PreparseField.php(118): craft\web\ErrorHandler->handleError()
#2 /vendor/yiisoft/yii2/base/Event.php(312): besteadfast\preparsefield\PreparseField->besteadfast\preparsefield\{closure:/vendor/besteadfast/craft-preparse-field/src/PreparseField.php:109-145}()
#3 /vendor/yiisoft/yii2/base/Event.php(312): ::call_user_func:{/vendor/yiisoft/yii2/base/Event.php:312}()
#4 /vendor/yiisoft/yii2/base/Component.php(637): yii\base\Event::trigger()
#5 /vendor/craftcms/cms/src/services/Elements.php(2599): craft\services\Elements->trigger()
#6 /vendor/craftcms/cms/src/services/Elements.php(755): craft\services\Elements->_saveElementInternal()
#7 /vendor/craftcms/cms/src/services/Globals.php(379): craft\services\Elements->saveElement()
#8 /vendor/craftcms/cms/src/base/ApplicationTrait.php(1654): craft\services\Globals->handleChangedGlobalSet()
#9 /vendor/craftcms/cms/src/services/ProjectConfig.php(1166): craft\web\Application->craft\base\{closure:/vendor/craftcms/cms/src/base/ApplicationTrait.php:1653-1655}()
#10 /vendor/yiisoft/yii2/base/Component.php(628): craft\services\ProjectConfig->handleChangeEvent()
#11 /vendor/yiisoft/yii2/base/Component.php(628): ::call_user_func:{/vendor/yiisoft/yii2/base/Component.php:628}()
#12 /vendor/craftcms/cms/src/services/ProjectConfig.php(728): craft\services\ProjectConfig->trigger()
#13 /vendor/craftcms/cms/src/services/ProjectConfig.php(510): craft\services\ProjectConfig->_processConfigChangesInternal()
#14 /vendor/craftcms/cms/src/services/Globals.php(304): craft\services\ProjectConfig->set()
#15 /vendor/craftcms/cms/src/controllers/GlobalsController.php(81): craft\services\Globals->saveSet()
#16 /vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\GlobalsController->actionSaveSet()
#17 /vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#18 /vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#19 /vendor/craftcms/cms/src/web/Controller.php(190): craft\controllers\GlobalsController->runAction()
#20 /vendor/yiisoft/yii2/base/Module.php(534): craft\controllers\GlobalsController->runAction()
#21 /vendor/craftcms/cms/src/web/Application.php(274): craft\web\Application->runAction()
#22 /vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#23 /vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#24 /vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#25 /public/index.php(22): craft\web\Application->run()
#26 {main}

**Comment by martinleveille** [comment]
Same error here with version 1.2.4 on Craft Pro 3.6.7 / PHP 7.4.15.

**Comment by jsunsawyer** [comment]
Checking in with the same error.

**Comment by codewithkyle** [comment]
Same error on Preparse 1.2.4 with Craft CMS 3.5.17.1 and PHP 7.4.3

**Comment by zizther** [comment]
Same issue with Preparse 1.2.4 with Craft CMS 3.6.10 and PHP 7.4.2

**Comment by johnwbaxter** [comment]
I have the same issue here

**Comment by iwe-hi** [comment]
Same issue with Preparse 1.2.4 with Craft CMS 3.6.13 and PHP 7.3.24

**Comment by jalendport** [comment]
Hey all, just wanted to let you know that we've found a potential solution for this; just want to do some testing and maybe get some additional eyes on it from some people that are much smarter than I am so we don't cause a regression for #66. Look for something early next week 🤞

**Comment by nickdunn** [comment]
@jalendport were you able to get extra 👀 on this?

**Comment by sunshad0w** [comment]
+ the same

**Comment by bfjare** [comment]
Has this been resolved?

**Comment by bkmorse** [comment]
Running into same issue.

**Comment by jalendport** [comment]
Hey everyone, thanks for your patience ❤️  - just released version 1.2.5 which fixes this bug :tada:

**Comment by bfjare** [comment]
@jalendport thanks for the work on this good sir!
