### ISSUE TITLE
Prevents completion of Commerce Orders when "parse before save" setting is disabled.

### ISSUE THREAD

**Issue by yoannisj** [besteadfast/craft-preparse-field#72]
After updating from v1.2.2 to v1.2.4, trying to complete a craft commerce order by posting to the commerce/payments/pay action throws a 'No order Adjustment exists with the ID “X”' error, if the Order element field layout contains a Preparse Field with the "parse before save" setting disabled.

I reported the problem in another craft commerce [issue](https://github.com/craftcms/commerce/issues/1116) as well, but open this issue here in case the problem can be fixed in the preparse-field's code-base.

**Comment by engram-design** [comment]
Just hit this (again), so locking to 1.2.2 fixes it for the moment.

**Comment by jalendport** [comment]
Just released version 1.2.5 which fixes this bug :tada:
