### ISSUE TITLE
Parse just once, then never again

### ISSUE THREAD

**Issue by nickdunn** [besteadfast/craft-preparse-field#79]
Is it possible to set a Preparse field to parse the first time an entry is saved, but once the field has a value, to not process again? I want to generate a random number once and it to never change.

**Comment by mmikkel** [comment]
There's no feature like that built into Preparse, but a viable workaround could be to only generate a new number in the field's Twig template, if the field doesn't already have a value (the below assumes your Preparse field's handle is `myPreparseField`):

```twig
{{ element.myPreparseField|default(random(9999999999)) }}
```
