### ISSUE TITLE
Multiple preparse fields trigger multiple element saves.

### ISSUE THREAD

**Issue by leevigraham** [besteadfast/craft-preparse-field#89]
If an element has multiple pre-parse fields, the element is saved once for initial save and then once for every preparse field. This can cause a perf issue if the element has custom behaviours that trigger queue jobs or cache clearing functionality.

**Comment by philipboomy** [comment]
I am about to add a second pre-parse field but I guess I shouldn't as I use Blitz. Did you find a workaround?

**Comment by leevigraham** [comment]
@philipboomy Probably best you check this one yourself on your own implementation. I can't remember now if this was really caused by preparse or some other custom module.
